{
 "title": "Plant performance",
 "time": { "from": "2025-06-27T15:45:07.955Z", "to": "2025-06-27T15:45:44.202Z" },
 "panels": [
  {
   "title": "CO2_Panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"co2_capture\")\r\n  |> filter(fn: (r) => r._field == \"co2_concentration\")"
    }
   ]
  },
  {
   "title": "Co2_Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"co2_capture\")\r\n  |> filter(fn: (r) => r._field == \"co2_concentration\")"
    }
   ]
  },
  {
   "title": "Pressure_Panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"co2_capture\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")"
    }
   ]
  },
  {
   "title": "Temperature Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"co2_capture\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Temperature_Panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"co2_capture\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Pressure Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"co2_capture\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")"
    }
   ]
  }
 ]
}